### ISSUE TITLE
Fixed?

### ISSUE THREAD

**Issue by ptmt** [beretboat/RNDLayoutIssue#1]
Could you please test it on 0.3.15?

I used various test cases such this:

``` js
componentDidMount() {
    const remove = j => {
      this._remove();
      if (j > 0) {
        setTimeout(() => remove(j - 1), 100);
      } else {
        setTimeout(() => this._add(), 1000);
        setTimeout(() => this._add(), 1100);
        setTimeout(() => this._add(), 1200);
      }
    }
    remove(10);
  },
```

**Comment by beretboat** [comment]
Thanks for the effort! Just tried 0.3.15, but unfortunately I still see the problem:
![sc](https://cloud.githubusercontent.com/assets/4593681/13383903/07675a8c-decb-11e5-82e5-1376dd50119a.png)

**Comment by ptmt** [comment]
Interesting, my test scenarios has passed. Will write another bunch of it (it's hard to debug with manual clicking each time), or may I'm just missing something out. Thanks again for this repository.

**Comment by beretboat** [comment]
I tried your scenario above but it did not pass. Could it be a environment issue? 
It looks OK seemingly, I need to view-debug it in Xcode to see the problem:
![sc](https://cloud.githubusercontent.com/assets/4593681/13388486/43147512-defb-11e5-993d-6c2e355c0160.png)

**Comment by ptmt** [comment]
I was finally able to recreate the issue, it depends on the speed of views deletion. There is inconsistent state between `ShadowView` and its correspond `View` (which doesn't removeFromSuperView itself).  So, yeah, it's sort of an environment issue. It also explains why I have seen this before when I interacted with apps fast. 
My plan is:
— Write tests scenario when even 1ms matters.
— Fix (give me a day or two, I hope).
— Publish next version RN and also upload my tests here. 

By the way, transparent views / or texts controls helps to see that faster and iterate without XCode debugging:
![screenshot 2016-02-29 13 58 56](https://cloud.githubusercontent.com/assets/1004115/13392584/98c809ce-deec-11e5-89e5-7dcd0c2d981e.png)

**Comment by beretboat** [comment]
Transparent control is a good idea. Thanks.

**Comment by ptmt** [comment]
Looks like there was a three different issues. Two of them related to concurrent problems and one to animation. I fixed it locally and now tested heavily. If you have an idea how it could be tested let me know. I'm cleaning and preparing commit now.

**Comment by beretboat** [comment]
Oh, that was quick. Can't wait to try it out.

**Comment by ptmt** [comment]
Pushed the commit. Could you check it with package installed from `master` branch (do not want to publish on npm yet)?

**Comment by beretboat** [comment]
Sorry, I'm a little confuse. Do you mean the fix the the [PR](https://github.com/beretboat/RNDLayoutIssue/pull/2) to this repo? So the problem is not in react-native-desktop, but it's in this test app?

**Comment by ptmt** [comment]
Sorry, fix is in the main RND repo, just use 'ptmt/react-native-desktop'
instead of version in package.json

**Comment by beretboat** [comment]
I was confuse because I haven't seem the commit yet. Maybe there's latency in CDN.

**Comment by ptmt** [comment]
sorry again, long day. Pushed now

**Comment by beretboat** [comment]
Tested for a few minutes, so far so good. Great work, thank you!

**Comment by ptmt** [comment]
Ok, I've published it on npm as 0.3.16. Thank you again.

**Comment by beretboat** [comment]
If you got time, would you mind explain a little bit? What's the problem in the deleted code?
 -    dispatch_async( dispatch_get_main_queue(), ^{
 -      [self addSubview:view];
 -      [view setNeedsDisplay:YES];
 -    });
 +    // TODO: race conditions here?
 +    NSMutableArray *array = [self.subviews mutableCopy];
 +    [array insertObject:view atIndex:atIndex];
 +    self.subviews = array;
 +    [view setNeedsDisplay:YES];

**Comment by ptmt** [comment]
I explained it in the commit message. Basically, there are two problems here: 
1. Do not add subview in the main thread, to avoid inconsistency (I debug a lot to find why, in short, UIManager can't see views sometimes) 
2. CocoaTouch (so react-native) has a method for `UIView` which we do not have here in Cocoa (react-native-desktop), so sometimes it's important to insert an object at the exact index. So we make mutableCopy and insert element into array.

**Comment by beretboat** [comment]
Sorry, I didn't see your explanation in the commit. please ignore my last comment.
